name: Sync Master back with Develop Branch
on:
  push:
    branches:
    - master

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Master
      uses: actions/checkout@v2
    - name: Create The Pull Request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "develop"
        pr_title: "Syncing ${{ github.ref }} back to other environments"
        github_token: ${{ secrets.GITHUB_TOKEN }}
