name: Sync Master back with Develop Branch
on:
  push:
    branches:
      - master
jobs:
  syncBack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: develop
          title: 'Syncinc Back From Master'
          commit-message: 'chore: Sync Back'
